export const SEARCH_BOOKS_START = 'SEARCH_BOOKS_START';
export const SEARCH_BOOKS_SUCCESS = 'SEARCH_BOOKS_SUCCESS';
export const SEARCH_BOOKS_FAIL = 'SEARCH_BOOKS_FAIL';
export const SEARCH_BOOKS_CLEANUP = 'SEARCH_BOOKS_CLEANUP';

export const GET_SINGLE_BOOKS_START = 'GET_SINGLE_BOOKS_START';
export const GET_SINGLE_BOOKS_SUCCESS = 'GET_SINGLE_BOOKS_SUCCESS';
export const GET_SINGLE_BOOKS_FAIL = 'GET_SINGLE_BOOKS_FAIL';
export const GET_SINGLE_BOOKS_CLEANUP = 'GET_SINGLE_BOOKS_CLEANUP';

export const ADD_BOOK_TO_FAV = 'ADD_BOOK_TO_FAV';
export const REMOVE_BOOK_FROM_FAV = 'REMOVE_BOOK_FROM_FAV';
